// Generated by gencpp from file good_jackal/Tracked_Object.msg
// DO NOT EDIT!


#ifndef GOOD_JACKAL_MESSAGE_TRACKED_OBJECT_H
#define GOOD_JACKAL_MESSAGE_TRACKED_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace good_jackal
{
template <class ContainerAllocator>
struct Tracked_Object_
{
  typedef Tracked_Object_<ContainerAllocator> Type;

  Tracked_Object_()
    : header()
    , x(0)
    , y(0)
    , r(0)  {
    }
  Tracked_Object_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0)
    , y(0)
    , r(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _r_type;
  _r_type r;




  typedef boost::shared_ptr< ::good_jackal::Tracked_Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::good_jackal::Tracked_Object_<ContainerAllocator> const> ConstPtr;

}; // struct Tracked_Object_

typedef ::good_jackal::Tracked_Object_<std::allocator<void> > Tracked_Object;

typedef boost::shared_ptr< ::good_jackal::Tracked_Object > Tracked_ObjectPtr;
typedef boost::shared_ptr< ::good_jackal::Tracked_Object const> Tracked_ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::good_jackal::Tracked_Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::good_jackal::Tracked_Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace good_jackal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'good_jackal': ['/home/ros/EE5900_Repos/good-jackal/lab_6_ws/src/good_jackal/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::good_jackal::Tracked_Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::good_jackal::Tracked_Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::good_jackal::Tracked_Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::good_jackal::Tracked_Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::good_jackal::Tracked_Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::good_jackal::Tracked_Object_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::good_jackal::Tracked_Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "786c00b2cab433480b4bf538c597245e";
  }

  static const char* value(const ::good_jackal::Tracked_Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x786c00b2cab43348ULL;
  static const uint64_t static_value2 = 0x0b4bf538c597245eULL;
};

template<class ContainerAllocator>
struct DataType< ::good_jackal::Tracked_Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "good_jackal/Tracked_Object";
  }

  static const char* value(const ::good_jackal::Tracked_Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::good_jackal::Tracked_Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int64 x\n\
int64 y\n\
int64 r\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::good_jackal::Tracked_Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::good_jackal::Tracked_Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tracked_Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::good_jackal::Tracked_Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::good_jackal::Tracked_Object_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "r: ";
    Printer<int64_t>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOOD_JACKAL_MESSAGE_TRACKED_OBJECT_H
